name: Build & Push Docker image

on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: "Tag name for docker image"
        required: true
        type: string
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: [self-hosted, Linux, X64, orion]

    env:
      VERSION_TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version-tag || github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get repository name without owner
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | sed 's/.*\///')
          echo REPO_NAME=$REPO_NAME >> $GITHUB_ENV

      - name: Print trigger information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Using version tag: ${{ env.VERSION_TAG }}"

      - name: Setup Bunjs
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: ./frontend
        run: bun i --silent

      - name: Type checking
        working-directory: ./frontend
        run: bun run tsc

      - name: Lint code
        working-directory: ./frontend
        run: bun run lint --quiet

      - name: Logging in to Docker Hub
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: docker build . -t owner/${{ env.REPO_NAME }}:${{ env.VERSION_TAG }}

      - name: Push the Docker image
        run: docker push owner/${{ env.REPO_NAME }}:${{ env.VERSION_TAG }}
