name: Build & Push Docker image

on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: "Tag name for docker image"
        required: true
        type: string
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build and push Docker image
    runs-on: [self-hosted, Linux, X64, orion]

    env:
      VERSION_TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version-tag || github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Get image name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | sed 's/.*\///')
          echo REPO_NAME=$REPO_NAME >> $GITHUB_ENV

      - name: Logging in to Docker Hub
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: docker build . -t owner/${{ env.REPO_NAME }}:${{ env.VERSION_TAG }}

      - name: Push the Docker image
        run: docker compose push
